"use client";

import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import "./public-home.css";

type Branch = { id: string; name: string; address: string | null };
type DanceClass = { id: string; branch_id: string; name: string; status: string; schedule_days: string[] | null; schedule_start: string | null; schedule_end: string | null };
type Teacher = { id: string; full_name: string; avatar_url: string | null; status: string };
const days: Record<string, string> = { "2": "Thứ 2", "3": "Thứ 3", "4": "Thứ 4", "5": "Thứ 5", "6": "Thứ 6", "7": "Thứ 7", "0": "Chủ nhật" };
const benefits = [["◌", "Vận động & sức khỏe", "Khơi dậy tình yêu vận động qua từng buổi học."], ["♫", "Cảm thụ âm nhạc", "Lắng nghe nhịp điệu và thể hiện bằng cơ thể."], ["◎", "Khả năng tập trung", "Rèn sự chú ý qua những tổ hợp động tác mới."], ["↗", "Làm việc nhóm", "Cùng nhau phối hợp, tôn trọng và tỏa sáng."], ["✦", "Sự tự tin", "Từng bước dám thử, dám thể hiện bản thân."], ["♥", "Niềm vui vận động", "Một không gian tích cực cho niềm vui mỗi ngày."]];
const faqs = [["Bé bao nhiêu tuổi có thể tham gia?", "Độ tuổi phù hợp sẽ tùy theo từng lớp. Hãy để lại thông tin, ANGEL BK sẽ tư vấn lớp phù hợp với bé."], ["Người mới có học được không?", "Có. Việc bắt đầu từ nền tảng sẽ được cân nhắc khi tư vấn lớp cho bé."], ["Một buổi học kéo dài bao lâu?", "Thời lượng được công bố theo lịch của từng lớp. Bạn có thể xem lịch bên dưới hoặc đăng ký để được tư vấn."], ["Có thể học thử không?", "Có thể gửi yêu cầu đăng ký học thử qua biểu mẫu. Đội ngũ ANGEL BK sẽ liên hệ để xác nhận."], ["Làm sao để xem lịch học?", "Lịch của các lớp đang mở được hiển thị trong phần Lịch học khi dữ liệu sẵn sàng."]];
function schedule(item: DanceClass) { if (!item.schedule_days?.length) return "Lịch đang cập nhật"; const d = item.schedule_days.map((day) => days[day] ?? day).join(" · "); return item.schedule_start && item.schedule_end ? `${d}, ${item.schedule_start.slice(0, 5)}–${item.schedule_end.slice(0, 5)}` : d; }

export default function PublicHome() {
  const supabase = useMemo(() => createClient(), []);
  const [branches, setBranches] = useState<Branch[]>([]); const [classes, setClasses] = useState<DanceClass[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [menu, setMenu] = useState(false); const [faq, setFaq] = useState<number | null>(0);
  const [form, setForm] = useState({ parentName: "", childName: "", age: "", phone: "", classId: "", branchId: "", note: "" });
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  useEffect(() => { async function load() { const [b, c, t] = await Promise.all([supabase.from("branches").select("id,name,address").order("name"), supabase.from("classes").select("id,branch_id,name,status,schedule_days,schedule_start,schedule_end").eq("status", "active").order("name"), supabase.from("teachers").select("id,full_name,avatar_url,status").eq("status", "active").order("full_name")]); if (!b.error) setBranches(b.data ?? []); if (!c.error) setClasses(c.data ?? []); if (!t.error) setTeachers(t.data ?? []); } load(); }, [supabase]);
  const branchMap = useMemo(() => new Map(branches.map((b) => [b.id, b.name])), [branches]);
  const update = (key: keyof typeof form, value: string) => { setForm((old) => ({ ...old, [key]: value })); setState("idle"); };
  const goToForm = () => { setMenu(false); document.getElementById("dang-ky")?.scrollIntoView({ behavior: "smooth" }); };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (state === "loading") return; if (!form.parentName.trim() || !form.childName.trim() || !form.age.trim() || !form.phone.trim()) { setState("error"); setMessage("Vui lòng điền đủ các trường bắt buộc."); return; } if (!/^[0-9+\s().-]{8,}$/.test(form.phone.trim())) { setState("error"); setMessage("Vui lòng nhập số điện thoại hợp lệ."); return; } setState("loading"); await new Promise((r) => setTimeout(r, 400)); setState("error"); setMessage("Hệ thống tiếp nhận đăng ký đang được kết nối. Vui lòng liên hệ ANGEL BK để được hỗ trợ học thử."); }
  return <div className="angel-site">
    <header className="angel-header"><a href="#dau-trang" className="angel-logo" aria-label="ANGEL BK - Trang chủ"><span>ANGEL</span><small>BK · DANCE</small></a><button className="angel-menu" type="button" aria-expanded={menu} onClick={() => setMenu(!menu)}><span /><span /><span /><i className="sr-only">Mở menu</i></button><nav className={menu ? "angel-nav is-open" : "angel-nav"} aria-label="Điều hướng chính"><a href="#lop-hoc" onClick={() => setMenu(false)}>Lớp học</a><a href="#lich-hoc" onClick={() => setMenu(false)}>Lịch học</a><a href="#hanh-trinh" onClick={() => setMenu(false)}>Hành trình</a><a href="#faq" onClick={() => setMenu(false)}>Giải đáp</a><button type="button" className="angel-button small" onClick={goToForm}>Đăng ký học thử</button></nav></header>
    <main id="dau-trang">
      <section className="angel-hero"><div className="hero-copy"><p className="eyebrow">CLB NHẢY DÀNH CHO CÁC BẠN NHỎ</p><h1>ANGEL <em>BK</em></h1><p className="hero-slogan">Mỗi bước nhảy –<br />một bước trưởng thành.</p><p className="hero-intro">Nơi các bạn nhỏ khám phá nhịp điệu, chuyển động và niềm vui được là chính mình.</p><div className="hero-actions"><button className="angel-button" onClick={goToForm}>Đăng ký học thử <b>→</b></button><a href="#lop-hoc" className="angel-link">Xem các lớp học <b>↓</b></a></div></div><div className="hero-visual" role="img" aria-label="Không gian hình ảnh ANGEL BK, sẵn sàng thay bằng ảnh hoặc video thật"><div className="orb one" /><div className="orb two" /><div className="hero-frame"><span>ANGEL BK</span><small>YOUR MOMENT TO MOVE</small></div><p>Ảnh/video nổi bật<br /><small>Thay tại components/public/public-home.tsx</small></p></div></section>
      <section className="angel-section benefits"><div className="section-heading"><p className="eyebrow">KHÔNG CHỈ LÀ NHỮNG BƯỚC NHẢY</p><h2>Mỗi buổi học là một<br /><em>khoảng trời mới.</em></h2></div><div className="benefit-grid">{benefits.map(([icon, title, text]) => <article className="benefit-card" key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="angel-section class-time"><div className="class-time-visual"><div className="video-placeholder"><button aria-label="Phát video giới thiệu" type="button">▶</button><p>VIDEO / HÌNH ẢNH BUỔI HỌC</p><small>Thay bằng media thật trong public/ANGEL-BK-WEBSITE/video/</small></div></div><div className="class-time-copy"><p className="eyebrow">MỘT BUỔI HỌC TẠI ANGEL BK</p><h2>Khởi động,<br /><em>khám phá và tỏa sáng.</em></h2><p>Không gian nội dung này được thiết kế sẵn để đội ngũ bổ sung ảnh hoặc video chân thực về từng buổi học sau này.</p><ol><li><b>01</b> Chào đón & khởi động</li><li><b>02</b> Làm quen nhịp điệu, động tác</li><li><b>03</b> Luyện tập cùng nhóm</li><li><b>04</b> Thả lỏng & nhìn lại buổi học</li></ol></div></section>
      <section className="angel-section classes" id="lop-hoc"><div className="section-heading split"><div><p className="eyebrow">TÌM LỚP PHÙ HỢP</p><h2>Các lớp học<br /><em>đang mở.</em></h2></div><p>Thông tin lớp được lấy từ hệ thống quản lý hiện có khi dữ liệu được cấp quyền công khai.</p></div>{classes.length ? <div className="class-grid">{classes.map((item, index) => <article className="class-card" key={item.id}><div className={`class-image image-${index % 3}`}><span>ANGEL BK</span></div><div className="class-card-body"><p className="card-kicker">{branchMap.get(item.branch_id) ?? "Cơ sở đang cập nhật"}</p><h3>{item.name}</h3><dl><div><dt>Lịch học</dt><dd>{schedule(item)}</dd></div><div><dt>Thông tin</dt><dd>Độ tuổi, trình độ sẽ được tư vấn phù hợp</dd></div></dl><button className="text-button" onClick={goToForm}>Đăng ký học thử <b>→</b></button></div></article>)}</div> : <Empty title="Thông tin lớp đang được cập nhật" text="Hãy để lại nhu cầu học thử để ANGEL BK tư vấn lớp phù hợp cho bé." action={goToForm} />}</section>
      <section className="angel-section teachers"><div className="section-heading"><p className="eyebrow">ĐỒNG HÀNH CÙNG BÉ</p><h2>Giáo viên<br /><em>ANGEL BK.</em></h2></div>{teachers.length ? <div className="teacher-grid">{teachers.map((teacher) => <article className="teacher-card" key={teacher.id}>{teacher.avatar_url ? <Image src={teacher.avatar_url} alt={teacher.full_name} width={480} height={560} unoptimized /> : <div className="teacher-placeholder" aria-hidden="true">{teacher.full_name.slice(0, 1)}</div>}<div><p>GIÁO VIÊN</p><h3>{teacher.full_name}</h3><span>Thông tin bộ môn và phong cách giảng dạy đang cập nhật</span></div></article>)}</div> : <Empty title="Hồ sơ giáo viên sẽ sớm được cập nhật" text="Chúng tôi chỉ hiển thị thông tin chính xác, đã được ANGEL BK xác nhận." />}</section>
      <section className="angel-section moments"><div className="section-heading split"><div><p className="eyebrow">KHOẢNH KHẮC ANGEL BK</p><h2>Chờ những câu chuyện<br /><em>thật được kể.</em></h2></div><p>Thư viện ảnh/video được để trống có chủ đích, sẵn sàng nhận nội dung thật từ hoạt động của CLB.</p></div><div className="moment-grid"><div className="moment-one">HỌC VIÊN<small>Ảnh thật sắp bổ sung</small></div><div className="moment-two">LỚP HỌC<small>Ảnh thật sắp bổ sung</small></div><div className="moment-three">VIDEO<small>Video thật sắp bổ sung</small></div></div></section>
      <section className="angel-section journey" id="hanh-trinh"><p className="eyebrow">HÀNH TRÌNH HỌC VIÊN</p><h2>Bắt đầu từ một<br /><em>nhịp đếm nhỏ.</em></h2><div className="journey-track">{["Ngày đầu", "Làm quen", "Tiến bộ", "Tự tin", "Biểu diễn"].map((step, index) => <div className="journey-step" key={step}><span>0{index + 1}</span><strong>{step}</strong></div>)}</div></section>
      <section className="angel-section schedule" id="lich-hoc"><div className="section-heading split"><div><p className="eyebrow">LỊCH HỌC</p><h2>Chọn nhịp điệu<br /><em>phù hợp.</em></h2></div><button className="angel-button outline" onClick={goToForm}>Nhận tư vấn lịch học</button></div>{classes.length ? <div className="schedule-list">{classes.map((item) => <article key={item.id}><div><span>{branchMap.get(item.branch_id) ?? "Cơ sở"}</span><h3>{item.name}</h3></div><p>{schedule(item)}</p><button className="text-button" onClick={goToForm}>Đăng ký <b>→</b></button></article>)}</div> : <Empty title="Chưa có lịch công khai" text="Để lại thông tin để được tư vấn lịch học phù hợp." action={goToForm} />}</section>
      <section className="angel-section future-sections"><div><p className="eyebrow">THÀNH TÍCH & HOẠT ĐỘNG</p><h2>Những dấu mốc<br /><em>sẽ được cập nhật.</em></h2><p>ANGEL BK chưa có dữ liệu công khai phù hợp để hiển thị tại đây.</p></div><div><p className="eyebrow">PHỤ HUYNH NÓI GÌ</p><h2>Lắng nghe từ<br /><em>những trải nghiệm thật.</em></h2><p>Nhận xét sẽ chỉ xuất hiện khi có sự đồng ý và nội dung xác thực từ phụ huynh.</p></div></section>
      <section className="angel-section faq" id="faq"><div className="section-heading"><p className="eyebrow">GIẢI ĐÁP NHANH</p><h2>Bạn đang<br /><em>băn khoăn điều gì?</em></h2></div><div className="faq-list">{faqs.map(([question, answer], index) => <article key={question} className={faq === index ? "open" : ""}><button type="button" aria-expanded={faq === index} onClick={() => setFaq(faq === index ? null : index)}><span>{question}</span><b>{faq === index ? "−" : "+"}</b></button>{faq === index && <p>{answer}</p>}</article>)}</div></section>
      <section className="angel-section signup" id="dang-ky"><div className="signup-copy"><p className="eyebrow">BẮT ĐẦU HÀNH TRÌNH</p><h2>Sẵn sàng cho<br /><em>bước nhảy đầu tiên?</em></h2><p>Để lại thông tin để ANGEL BK có thể tư vấn lớp học phù hợp nhất cho bé.</p><div className="signup-deco">ANGEL<br />BK</div></div><form className="signup-form" onSubmit={submit} noValidate><Field label="Tên phụ huynh" value={form.parentName} onChange={(v) => update("parentName", v)} required /><Field label="Tên bé" value={form.childName} onChange={(v) => update("childName", v)} required /><div className="two-fields"><Field label="Tuổi/năm sinh" value={form.age} onChange={(v) => update("age", v)} required placeholder="VD: 7 tuổi / 2019" /><Field label="Số điện thoại" value={form.phone} onChange={(v) => update("phone", v)} required inputMode="tel" /></div><div className="two-fields"><label>Lớp quan tâm<select value={form.classId} onChange={(e) => update("classId", e.target.value)}><option value="">Chọn lớp</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Cơ sở<select value={form.branchId} onChange={(e) => update("branchId", e.target.value)}><option value="">Chọn cơ sở</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label></div><label>Ghi chú<textarea value={form.note} onChange={(e) => update("note", e.target.value)} rows={3} placeholder="Điều bạn muốn ANGEL BK biết thêm" /></label>{state !== "idle" && <p className={`form-message ${state}`} role="status">{state === "loading" ? "Đang kiểm tra thông tin..." : message}</p>}<button className="angel-button submit" type="submit" disabled={state === "loading"}>{state === "loading" ? "Đang gửi..." : "Đăng ký học thử"} <b>→</b></button><small>Bằng việc gửi biểu mẫu, bạn đồng ý để ANGEL BK liên hệ tư vấn về lớp học.</small></form></section>
    </main><footer className="angel-footer"><a href="#dau-trang" className="angel-logo"><span>ANGEL</span><small>BK · DANCE</small></a><p>© {new Date().getFullYear()} ANGEL BK. Mỗi bước nhảy – một bước trưởng thành.</p><a href="#dau-trang">Lên đầu trang ↑</a></footer></div>;
}
function Empty({ title, text, action }: { title: string; text: string; action?: () => void }) { return <div className="empty-panel"><span>✦</span><h3>{title}</h3><p>{text}</p>{action && <button className="text-button" onClick={action}>Đăng ký nhận tư vấn <b>→</b></button>}</div>; }
function Field({ label, value, onChange, required, placeholder, inputMode }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; placeholder?: string; inputMode?: "tel" }) { return <label>{label} {required && <sup>*</sup>}<input value={value} onChange={(e) => onChange(e.target.value)} required={required} placeholder={placeholder} inputMode={inputMode} /></label>; }
