"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { vietnamCurrentMonth, vietnamToday } from "@/lib/vietnam-date";
type Branch={id:string;name:string};
type Revenue={id:string;revenue_date:string;category:string;description:string;payer_name:string|null;amount:number;payment_method:string|null;branch_id:string|null;note:string|null;created_at:string;branch?:{id:string;name:string}|null};
const CATEGORIES=[['room_rental','🏠 Cho thuê phòng'],['workshop','🎤 Workshop / Khóa ngắn hạn'],['event','🎪 Sự kiện / Biểu diễn'],['equipment','🎛️ Cho thuê thiết bị'],['materials','📦 Giáo trình / Tài liệu'],['partnership','🤝 Hợp tác / Đối tác'],['other','💵 Khoản thu khác']] as const;
const METHODS=[['cash','Tiền mặt'],['transfer','Chuyển khoản'],['other','Khác']] as const;
const money=(n:number)=>new Intl.NumberFormat('vi-VN').format(n)+' đ';
const categoryLabel=(v:string)=>CATEGORIES.find(([k])=>k===v)?.[1]??v;
const currentMonth = () => vietnamCurrentMonth();
export default function OtherRevenuePage(){
 const supabase=createClient(); const [rows,setRows]=useState<Revenue[]>([]); const [branches,setBranches]=useState<Branch[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [isAdmin,setIsAdmin]=useState(false); const [month,setMonth]=useState(currentMonth()); const [categoryFilter,setCategoryFilter]=useState(''); const [branchFilter,setBranchFilter]=useState(''); const [showForm,setShowForm]=useState(false); const [editing,setEditing]=useState<Revenue|null>(null);
 const blank={revenue_date:vietnamToday(),category:'room_rental',description:'',payer_name:'',amount:'',payment_method:'transfer',branch_id:'',note:''}; const [form,setForm]=useState(blank);
 async function loadData(){setLoading(true);const [a,b,r]=await Promise.all([supabase.auth.getUser(),supabase.from('branches').select('id,name').order('name'),supabase.from('other_revenues').select('id,revenue_date,category,description,payer_name,amount,payment_method,branch_id,note,created_at,branch:branch_id(id,name)').order('revenue_date',{ascending:false}).order('created_at',{ascending:false})]);if(b.error)alert('Không tải được cơ sở: '+b.error.message);if(r.error)alert('Không tải được khoản thu: '+r.error.message);if(a.data.user){const {data:p}=await supabase.from('profiles').select('role').eq('id',a.data.user.id).maybeSingle();setIsAdmin(p?.role==='admin')}setBranches(b.data??[]);setRows((r.data??[]) as unknown as Revenue[]);setLoading(false)}
 useEffect(()=>{loadData()},[]);
 const filtered=useMemo(()=>rows.filter(r=>r.revenue_date.startsWith(month)&&(!categoryFilter||r.category===categoryFilter)&&(!branchFilter||r.branch_id===branchFilter)),[rows,month,categoryFilter,branchFilter]);
 const total=filtered.reduce((s,r)=>s+Number(r.amount||0),0);
 function openCreate(){setEditing(null);setForm({...blank,revenue_date:vietnamToday()});setShowForm(true)}
 function openEdit(r:Revenue){setEditing(r);setForm({revenue_date:r.revenue_date,category:r.category,description:r.description,payer_name:r.payer_name??'',amount:String(r.amount),payment_method:r.payment_method??'transfer',branch_id:r.branch_id??'',note:r.note??''});setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();const amount=Number(form.amount);if(!form.description.trim())return alert('Vui lòng nhập nội dung khoản thu.');if(!Number.isFinite(amount)||amount<=0)return alert('Số tiền phải lớn hơn 0.');setSaving(true);const payload={revenue_date:form.revenue_date,category:form.category,description:form.description.trim(),payer_name:form.payer_name.trim()||null,amount,payment_method:form.payment_method,branch_id:form.branch_id||null,note:form.note.trim()||null};const result=editing?await supabase.from('other_revenues').update(payload).eq('id',editing.id):await supabase.from('other_revenues').insert(payload);setSaving(false);if(result.error)return alert('Không thể lưu khoản thu: '+result.error.message);setShowForm(false);await loadData()}
 async function remove(r:Revenue){if(!isAdmin)return alert('⛔ Chỉ ADMIN mới được xóa khoản thu.');if(!window.confirm(`Xóa khoản thu ${money(Number(r.amount))} — ${r.description}?`))return;const {error}=await supabase.from('other_revenues').delete().eq('id',r.id);if(error)return alert('Không thể xóa khoản thu: '+error.message);await loadData()}
 return <div className="space-y-6"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-black uppercase tracking-widest text-blue-600">TÀI CHÍNH</div><h1 className="mt-1 text-4xl font-black tracking-tight">💵 Thu khác</h1><p className="mt-2 text-slate-400">Quản lý các khoản thu ngoài học phí của CLB</p></div><button className="ui-btn ui-btn-blue" onClick={openCreate}>＋ Thêm khoản thu</button></section>
 <section className="grid gap-4 sm:grid-cols-3"><div className="ui-card p-5"><div className="text-sm font-semibold text-slate-500">💵 Tổng thu khác</div><div className="mt-2 text-2xl font-black text-emerald-700">{money(total)}</div></div><div className="ui-card p-5"><div className="text-sm font-semibold text-slate-500">🧾 Số giao dịch</div><div className="mt-2 text-2xl font-black">{filtered.length}</div></div><div className="ui-card p-5"><div className="text-sm font-semibold text-slate-500">📅 Kỳ xem</div><div className="mt-2 text-2xl font-black">{month.slice(5,7)}/{month.slice(0,4)}</div></div></section>
 <section className="ui-card p-4 sm:p-5"><div className="flex flex-wrap gap-3"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="ui-input"/><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)} className="ui-input"><option value="">Tất cả loại thu</option>{CATEGORIES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)} className="ui-input"><option value="">Tất cả cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div></section>
 <section className="ui-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b bg-slate-50 text-left text-xs font-black uppercase tracking-wide text-slate-500">{['Ngày','Nội dung','Loại','Người nộp','Cơ sở','Số tiền','Phương thức','Thao tác'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="px-5 py-10 text-center text-slate-400">Đang tải...</td></tr>:filtered.length===0?<tr><td colSpan={8} className="px-5 py-10 text-center text-slate-400">Chưa có khoản thu nào trong kỳ này.</td></tr>:filtered.map(r=><tr key={r.id} className="border-b last:border-0 hover:bg-slate-50/70"><td className="px-5 py-4 font-semibold">{r.revenue_date}</td><td className="px-5 py-4"><div className="font-black">{r.description}</div>{r.note&&<div className="mt-1 text-xs text-slate-400">{r.note}</div>}</td><td className="px-5 py-4">{categoryLabel(r.category)}</td><td className="px-5 py-4">{r.payer_name||'—'}</td><td className="px-5 py-4">{r.branch?.name||'Toàn CLB'}</td><td className="px-5 py-4 text-right font-black text-emerald-700">{money(Number(r.amount))}</td><td className="px-5 py-4">{METHODS.find(([k])=>k===r.payment_method)?.[1]??'—'}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button className="ui-btn" onClick={()=>openEdit(r)}>✏️ Sửa</button>{isAdmin&&<button className="ui-btn" onClick={()=>remove(r)}>🗑️ Xóa</button>}</div></td></tr>)}</tbody></table></div></section>
 {showForm&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">{editing?'✏️ Sửa khoản thu':'＋ Thêm khoản thu'}</h2><p className="mt-1 text-sm text-slate-400">Khoản thu này sẽ được cộng vào doanh thu.</p></div><button type="button" className="ui-btn" onClick={()=>setShowForm(false)}>Đóng</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Ngày thu<input type="date" value={form.revenue_date} onChange={e=>setForm({...form,revenue_date:e.target.value})} className="ui-input mt-1 w-full" required/></label><label className="text-sm font-bold">Loại khoản thu<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="ui-input mt-1 w-full">{CATEGORIES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">Nội dung<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="ui-input mt-1 w-full" placeholder="Ví dụ: Cho thuê phòng CN 15h–17h" required/></label><label className="text-sm font-bold">Người / đơn vị nộp<input value={form.payer_name} onChange={e=>setForm({...form,payer_name:e.target.value})} className="ui-input mt-1 w-full"/></label><label className="text-sm font-bold">Số tiền<input type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="ui-input mt-1 w-full" required/></label><label className="text-sm font-bold">Cơ sở<select value={form.branch_id} onChange={e=>setForm({...form,branch_id:e.target.value})} className="ui-input mt-1 w-full"><option value="">Toàn CLB / không gắn cơ sở</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-sm font-bold">Phương thức<select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})} className="ui-input mt-1 w-full">{METHODS.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">Ghi chú<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} className="ui-input mt-1 min-h-24 w-full"/></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="ui-btn" onClick={()=>setShowForm(false)}>Hủy</button><button disabled={saving} className="ui-btn ui-btn-blue">{saving?'Đang lưu...':'Lưu khoản thu'}</button></div></form></div>}</div>;
}
